# Configurando a Imagem
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "forwarded_port", guest: 80, host: 8085
  config.vm.network "public_network", ip: "192.168.0.13"  
  config.vm.provision "shell", inline:"cat /configs/id_bionic.pub >> .ssh/authorized_keys" 
  config.vm.synced_folder "./configs", "/configs" 
  config.vm.synced_folder  ".", "/vagrant", disabled: true
  config.vm.provision "shell", path:"./configs/script/script.sh"
  config.vm.provision "shell", inline:"ansible-playbook -i /configs/Ansible/hosts /configs/Ansible/playbook.yaml"  
end
  
  # config.vm.define "ansible" do |Ansible|

  # end
  # Definindo o servidor
  # config.vm.define "webserver" do |web|
  # web.vm.network "private_network", type: "dhcp" 
  # config.vm.network "private_network", ip: "192.168.50.4" --> utilizado para a comunicação com o host
